security:
    encoders:
        Queue\DataBundle\Entity\User: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, database]
        database:
            entity:
                class: Queue\DataBundle\Entity\User
        in_memory:
            memory:
                users:
                    demouser:  { password: demouser, roles: [ 'ROLE_USER' ] }
                    demoadmin: { password: demoadmin, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        standard:
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /check
                default_target_path: /
            logout:
                path: /logout
                target: /
            anonymous: true

    access_control:
        - { path: ^/admin, roles: ['ROLE_ADMIN']}
