<?php

namespace Queue\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Queue\DataBundle\Entity\Queue;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends EntityRepository
{
    public function findActiveByQueue(Queue $queue)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('entry')
            ->from('QueueDataBundle:Entry', 'entry')
            ->where('entry.isCompleted IS NULL')
            ->orderBy('entry.date')
            ->getQuery()
            ->getResult();
    }
}
