<?php

namespace Queue\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Queue\DataBundle\Entity\Queue;
use Queue\DataBundle\Entity\User;

/**
 * QueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QueueRepository extends EntityRepository
{
    public function hasActiveEntry(User $user, Queue $queue)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('entry')
            ->from('QueueDataBundle:Entry', 'entry')
            ->where('entry.queue = :queue')
            ->andWhere('entry.user = :user')
            ->andWhere('entry.isCompleted IS NULL')
            ->setParameters(array('queue' => $queue, 'user' => $user))
            ->getQuery()
            ->getResult();
    }
}
