parameters:
#    queue_web.example.class: Queue\WebBundle\Example

services:
#    queue_web.example:
#        class: %queue_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
